### ISSUE TITLE
It doesn't load user/password file properly

### ISSUE THREAD

**Issue by opabravo** [x90skysn3k/brutesprayx#4]
It didn't read the files supplied by `-u` and `-p` properly

![image](https://github.com/x90skysn3k/brutesprayx/assets/21262207/b44de276-e961-4bc9-8c29-e8e0409d43db)

The username and password files are not empty

```bash
┌──(bravosec㉿fsociety)-[~/pgplay/DC-9]
└─$ wc -l users.txt passwords.txt
 18 users.txt
 19 passwords.txt
 37 total
```

PS : file descriptor redirection works for those who want temporary solutions

![image](https://github.com/x90skysn3k/brutesprayx/assets/21262207/8f62dee9-e163-4678-ac14-a6b1bd11f758)

**Comment by x90skysn3k** [comment]
I have fixed this issue with v2.1.1 #5
