### ISSUE TITLE
join user and password files

### ISSUE THREAD

**Issue by jxdv** [x90skysn3k/brutesprayx#9]
Is there any particular reason why do you have the wordlist split into 2 files? Wouldn't it make more sense to just have one file and on each line you'd have `name:password`? While parsing the lines you'll just spit using `:`.  You'd save some time just by performing 1 file operation instead of 2.

**Comment by x90skysn3k** [comment]
most standard wordlists are not in this format, also that brings up a question. What if the wordlist has a username or password with a `:` inside. It makes more sense to keep them separate. However, it would be easy to add a flag for this functionality.

**Comment by jxdv** [comment]
> most standard wordlists are not in this format, also that brings up a question. What if the wordlist has a username or password with a `:` inside. It makes more sense to keep them separate. However, it would be easy to add a flag for this functionality.

Hmm, makes sense. Splitting would be difficult. Maybe a .csv file for that, but still doesn't really seem right to me.

**Comment by x90skysn3k** [comment]
the OG brutespray had a combo option with the -C argument, i'll work on adding it
